url: ""
timeout: 5 # 5 seconds
reconnect-delay: 60 # 1 minute
reconnect-multiplier: 1.3
time-format: "dd.MM HH:mm:ss"
time-zone: "Europe/Moscow"

messages:
  reload-failed: "&cFailed to reload: {}"
  reload-success: "&aSuccessfully reloaded"
  no-access: "&cUnknown command"
  status-state: "&aConnection state: &6{}"
  status-log-top: "&aLast 15 logs:"
  status-log-entry: "&7{} &8- &6{}{}" # time, type, additional
  status-log-added: " &a+{}"
  status-log-removed: " &a+{}"
  reconnecting: "&6Reconnecting.."
  reconnected: "&aReconnected!"
  reconnect-failed: "&cFailed to reconnect after {} seconds"